### ISSUE TITLE
Cut down usages of $ and get_node()

### ISSUE THREAD

**Issue by GutterCat42** [GutterCat42/blobs-with-guns-remastered#1]
This would be pretty performance inefficient right? Is it better to get_node() in a ready function and store the result in a variable which can be referenced later instead of get_node()-ing every time?

**Comment by a0fefd** [comment]
Probably set it in a ready function.

**Comment by GutterCat42** [comment]
Yep I agree, we'll do this from now on. As for the few existing scripts, do you want to modify them or shall I?

**Comment by GutterCat42** [comment]
I messed something up with branches
Hey, this is my first time using git ;)
Anyway I fixed it and its done now.
