### ISSUE TITLE
Is the facing variable really necessary?

### ISSUE THREAD

**Issue by GutterCat42** [GutterCat42/blobs-with-guns-remastered#10]
About the `facing` variable in `gun.tscn`

- Does it need to be exported?
- Does it need to be a Vector2?
- Do we need to update it every frame?
- Does it even need to exist? Can't we just use `get_parent().scale` directly?

I feel like the answer to the first three is "no" and the fourth is "quite possibly".

**Comment by a0fefd** [comment]
It's good practice using constants, exporting it is the main thing though, you can change that.

**Comment by GutterCat42** [comment]
But it's not a constant, it could change every frame depending on which direction the player is facing!
