### ISSUE TITLE
Audio rate for slow motion

### ISSUE THREAD

**Issue by GutterCat42** [GutterCat42/blobs-with-guns-remastered#13]
So I'm incorporating the slow motion and ran into this issue:
![image](https://github.com/GutterCat42/blobs-with-guns-remastered/assets/143992473/d97c2ea9-3ef6-4a2f-b4e7-4289c060bf88)
Engine time scale works fine, but it doesn't change the speed at which audio is replayed. From memory, I think this code works fine in Godot 3, but it doesn't seem to be working right now. How might one change the global audio rate in Godot 4?

My changes are in a new branch.

**Comment by a0fefd** [comment]
Try `AudioServer.playback_speed_scale` instead of `AudioServer.global_rate_scale`

**Comment by GutterCat42** [comment]
Can't believe I missed that... I must of been pretty tired
I said it was something obvious! Haha its fixed now, thanks :)
