### ISSUE TITLE
Reloading bug

### ISSUE THREAD

**Issue by GutterCat42** [GutterCat42/blobs-with-guns-remastered#14]
### How to reproduce:

Shoot and reload strategically until `ammo_in_mag == ammo`.
(The ammo display should show something like '8 | 8' - basically the numbers should be the same.)
Hit reload... and all your ammo disappears. Weird.

**I'm probably missing something really obvious here.**

**Comment by a0fefd** [comment]
Read this logic slowly and try to see what it is...
![image](https://github.com/GutterCat42/blobs-with-guns-remastered/assets/52446438/3b2fdb9b-bcbd-495a-86f3-3fdf554b7f2d)

**Comment by GutterCat42** [comment]
Just found that the same thing with some other numbers like '8 | 9'.

**Comment by GutterCat42** [comment]
Fixed by copying and pasting in the code from the original BWG.
