### ISSUE TITLE
Movement speed when firing quickly increases rapidly 

### ISSUE THREAD

**Issue by a0fefd** [GutterCat42/blobs-with-guns-remastered#6]
When firing (only gun currently is pistol) the movement speed rapidly increases, like really quick.

**Comment by GutterCat42** [comment]
Is it just because of the lack of a cooldown between shots? If so, I can fix that super fast.

**Comment by a0fefd** [comment]
It might be but it would be a great idea to add terminal velocity for all directions, and max horizontal velocity from recoil, which would be dependent on the gun being shot.

**Comment by GutterCat42** [comment]
Okay, I'll work on it.

**Comment by GutterCat42** [comment]
Alright, seems to be done :)

**Comment by a0fefd** [comment]
There is no timer...

**Comment by GutterCat42** [comment]
ShootTimer, a Timer node as a child of Gun?

**Comment by a0fefd** [comment]
![image](https://github.com/GutterCat42/blobs-with-guns-remastered/assets/52446438/5adab40e-c106-473f-ab34-d7c35232f609)
Not from what I see?

**Comment by GutterCat42** [comment]
Directly from the bottom of https://github.com/GutterCat42/blobs-with-guns-remastered/blob/main/scenes/guns/gun.tscn

![image](https://github.com/GutterCat42/blobs-with-guns-remastered/assets/143992473/f6841d9f-a21b-41b7-822a-f406574bb532)

**Comment by a0fefd** [comment]
![image](https://github.com/GutterCat42/blobs-with-guns-remastered/assets/52446438/fac02919-bf1d-4b2c-9898-522388da31a3)
Just now 😁
