### ISSUE TITLE
Do we need icon.svg in the project?

### ISSUE THREAD

**Issue by GutterCat42** [GutterCat42/blobs-with-guns-remastered#8]
Should we delete this file and its associated files in order to help make the game as lightweight as possible, or is it required by Godot?

**Comment by a0fefd** [comment]
I think you may as well just leave it there.

**Comment by GutterCat42** [comment]
Hmmm okay we'll leave it for now
Also sometime we need to make an .ico version of blobs_guns_thumbnail.png
But I'm gonna mark this as closed for now.
