### ISSUE TITLE
Is the splash screen too big?

### ISSUE THREAD

**Issue by GutterCat42** [GutterCat42/blobs-with-guns-remastered#9]
When I boot up Godot the logo is so massive and on the blue background it stands out so much that I feel like everybody behind me can see it

On the other hand, maybe that's good for marketing...

**Comment by a0fefd** [comment]
It's big, easy to see, it's great. But when you're booting up at school, at the front of the class, that's a different story...

Maybe make a branch without the massive screen so people have the choice for no screen or big screen (possibly even small screen).

**Comment by GutterCat42** [comment]
Hehe
Our new edition of the game
'Blobs with Guns: Covert Ops'

I feel like a whole branch just for changing one .png is overkill, I'll look into whether it is possible to change project settings from gdscript, in which case we can make an option in-game that dictates the size of the screen.

**Comment by GutterCat42** [comment]
Yep I'm fairly certain that it can be done
I'll have a go

**Comment by GutterCat42** [comment]
Its kinda half-baked right now, I'll merge it into the main branch but it wont be properly incorporated until the game is actually playable.
